/*
   This file was generated automatically by Alchitry Labs version 1.2.0.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [32-1:0] M_beta_ia;
  wire [32-1:0] M_beta_mem_data_address;
  wire [32-1:0] M_beta_mem_data_output;
  wire [1-1:0] M_beta_xwr;
  wire [32-1:0] M_beta_debug;
  reg [1-1:0] M_beta_slowclk;
  reg [1-1:0] M_beta_rst;
  reg [1-1:0] M_beta_interrupt;
  reg [32-1:0] M_beta_instruction;
  reg [32-1:0] M_beta_mem_data_input;
  beta_cpu_1 beta (
    .clk(clk),
    .slowclk(M_beta_slowclk),
    .rst(M_beta_rst),
    .interrupt(M_beta_interrupt),
    .instruction(M_beta_instruction),
    .mem_data_input(M_beta_mem_data_input),
    .ia(M_beta_ia),
    .mem_data_address(M_beta_mem_data_address),
    .mem_data_output(M_beta_mem_data_output),
    .xwr(M_beta_xwr),
    .debug(M_beta_debug)
  );
  
  wire [1-1:0] M_slowclock_value;
  counter_2 slowclock (
    .clk(clk),
    .rst(rst),
    .value(M_slowclock_value)
  );
  
  wire [1-1:0] M_slowclockedge_out;
  reg [1-1:0] M_slowclockedge_in;
  edge_detector_3 slowclockedge (
    .clk(clk),
    .in(M_slowclockedge_in),
    .out(M_slowclockedge_out)
  );
  
  localparam SAMPLE_CODE = 160'h7823fffb607f0020643f002090410800c03f0007;
  
  wire [32-1:0] M_memory_unit_data_memory_output;
  wire [32-1:0] M_memory_unit_instruction;
  reg [6-1:0] M_memory_unit_raddr;
  reg [6-1:0] M_memory_unit_waddr;
  reg [32-1:0] M_memory_unit_data_memory_input;
  reg [1-1:0] M_memory_unit_xwr;
  reg [6-1:0] M_memory_unit_ia;
  reg [1-1:0] M_memory_unit_instruction_write_enable;
  reg [32-1:0] M_memory_unit_instruction_towrite;
  memoryunit_4 memory_unit (
    .clk(clk),
    .raddr(M_memory_unit_raddr),
    .waddr(M_memory_unit_waddr),
    .data_memory_input(M_memory_unit_data_memory_input),
    .xwr(M_memory_unit_xwr),
    .ia(M_memory_unit_ia),
    .instruction_write_enable(M_memory_unit_instruction_write_enable),
    .instruction_towrite(M_memory_unit_instruction_towrite),
    .data_memory_output(M_memory_unit_data_memory_output),
    .instruction(M_memory_unit_instruction)
  );
  
  reg [2:0] M_writer_counter_d, M_writer_counter_q = 1'h0;
  
  
  localparam INSTRUCTIONLOAD_code_writer = 2'd0;
  localparam WAIT_code_writer = 2'd1;
  localparam GO_code_writer = 2'd2;
  
  reg [1:0] M_code_writer_d, M_code_writer_q = INSTRUCTIONLOAD_code_writer;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_5 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  always @* begin
    M_code_writer_d = M_code_writer_q;
    M_writer_counter_d = M_writer_counter_q;
    
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = {3'h0, io_button};
    usb_tx = usb_rx;
    io_led = 24'h000000;
    io_seg = 8'h00;
    io_sel = 4'h0;
    M_slowclockedge_in = M_slowclock_value;
    M_beta_interrupt = 1'h0;
    M_beta_slowclk = M_slowclockedge_out;
    M_beta_rst = 1'h0;
    io_led[0+7-:8] = M_beta_ia[0+7-:8];
    io_led[8+7-:8] = M_beta_mem_data_address[0+7-:8];
    io_led[16+7-:8] = M_beta_mem_data_output[0+7-:8];
    led[2+5-:6] = M_memory_unit_instruction[26+5-:6];
    led[0+2-:3] = M_memory_unit_data_memory_output;
    M_beta_instruction = M_memory_unit_instruction;
    M_beta_mem_data_input = M_memory_unit_data_memory_output;
    M_memory_unit_ia = M_beta_ia[0+31-:32];
    M_memory_unit_data_memory_input = M_beta_mem_data_output;
    M_memory_unit_xwr = M_beta_xwr;
    M_memory_unit_waddr = M_beta_mem_data_address[0+31-:32];
    M_memory_unit_raddr = M_beta_mem_data_address[0+31-:32];
    M_memory_unit_instruction_write_enable = 1'h0;
    M_memory_unit_instruction_towrite = 32'h00000000;
    
    case (M_code_writer_q)
      INSTRUCTIONLOAD_code_writer: begin
        M_beta_rst = 1'h1;
        M_writer_counter_d = M_writer_counter_q + 1'h1;
        M_memory_unit_instruction_towrite = SAMPLE_CODE[(M_writer_counter_q)*32+31-:32];
        M_memory_unit_instruction_write_enable = 1'h1;
        M_memory_unit_ia = M_writer_counter_q << 2'h2;
        if (M_writer_counter_q == 3'h4) begin
          M_code_writer_d = WAIT_code_writer;
        end
      end
      WAIT_code_writer: begin
        M_beta_rst = 1'h1;
        M_code_writer_d = GO_code_writer;
      end
      GO_code_writer: begin
        M_code_writer_d = GO_code_writer;
      end
    endcase
  end
  
  always @(posedge clk) begin
    M_code_writer_q <= M_code_writer_d;
  end
  
  
  always @(posedge clk) begin
    M_writer_counter_q <= M_writer_counter_d;
  end
  
endmodule
