/*
   This file was generated automatically by Alchitry Labs version 1.2.0.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seq_plus_two_withReset_2 (
    input clk,
    input rst,
    output reg [7:0] out
  );
  
  
  
  reg [7:0] M_register_1_d, M_register_1_q = 1'h0;
  
  wire [8-1:0] M_plus_two_s;
  wire [1-1:0] M_plus_two_cout;
  reg [8-1:0] M_plus_two_x;
  reg [8-1:0] M_plus_two_y;
  reg [1-1:0] M_plus_two_cin;
  eight_bit_adder_4 plus_two (
    .x(M_plus_two_x),
    .y(M_plus_two_y),
    .cin(M_plus_two_cin),
    .s(M_plus_two_s),
    .cout(M_plus_two_cout)
  );
  
  always @* begin
    M_register_1_d = M_register_1_q;
    
    M_plus_two_y = 8'h02;
    M_plus_two_x = M_register_1_q;
    M_plus_two_cin = 1'h0;
    M_register_1_d = M_plus_two_s;
    out = M_plus_two_s;
    if (rst == 1'h1) begin
      M_register_1_d = 1'h0;
    end
  end
  
  always @(posedge clk) begin
    M_register_1_q <= M_register_1_d;
  end
  
endmodule
