/*
   This file was generated automatically by Alchitry Labs version 1.1.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module fourbitadder_1 (
    input [3:0] a,
    input [3:0] b,
    output reg [4:0] out
  );
  
  
  
  always @* begin
    out = a + b;
  end
endmodule
