/*
   This file was generated automatically by Alchitry Labs version 1.2.0.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_11 (
    input [31:0] a,
    input [31:0] b,
    input [5:0] alufn_signal,
    output reg [31:0] out,
    output reg [0:0] z,
    output reg [0:0] v,
    output reg [0:0] n
  );
  
  
  
  reg [31:0] s;
  
  always @* begin
    s = 32'h00000000;
    
    case (alufn_signal[0+0-:1])
      1'h0: begin
        s = a + b;
      end
      1'h1: begin
        s = a - b;
      end
      default: begin
        s = 32'h00000000;
      end
    endcase
    n = s[31+0-:1];
    v = (a[31+0-:1] & (b[31+0-:1] ^ alufn_signal[0+0-:1]) & !s[31+0-:1]) | (!a[31+0-:1] & !(b[31+0-:1] ^ alufn_signal[0+0-:1]) & s[31+0-:1]);
    z = (~|s);
    out = s;
  end
endmodule
