/*
   This file was generated automatically by Alchitry Labs version 1.1.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module lightbox_4 (
    input clk,
    input b,
    output reg out
  );
  
  
  
  localparam OFF_lb = 1'd0;
  localparam ON_lb = 1'd1;
  
  reg M_lb_d, M_lb_q = OFF_lb;
  
  always @* begin
    M_lb_d = M_lb_q;
    
    M_lb_d = M_lb_q;
    out = 1'h0;
    
    case (M_lb_q)
      ON_lb: begin
        if (b == 1'h1) begin
          M_lb_d = OFF_lb;
        end
        out = 1'h1;
      end
      OFF_lb: begin
        if (b == 1'h1) begin
          M_lb_d = ON_lb;
        end
        out = 1'h0;
      end
    endcase
  end
  
  always @(posedge clk) begin
    M_lb_q <= M_lb_d;
  end
  
endmodule
