/*
   This file was generated automatically by Alchitry Labs version 1.2.0.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module game_miniRegfiles_12 (
    input clk,
    input rst,
    input [3:0] write_address,
    input we,
    input [15:0] data,
    input [3:0] read_address_a,
    input [3:0] read_address_b,
    output reg [15:0] out_a,
    output reg [15:0] out_b,
    output reg [15:0] out,
    output reg [31:0] all_scores,
    output reg [3:0] all_buttons,
    output reg [15:0] counter_out
  );
  
  
  
  reg [15:0] M_p1_score_d, M_p1_score_q = 1'h0;
  reg [15:0] M_p2_score_d, M_p2_score_q = 1'h0;
  reg [15:0] M_p1_buttonPress_d, M_p1_buttonPress_q = 1'h0;
  reg [15:0] M_p2_buttonPress_d, M_p2_buttonPress_q = 1'h0;
  reg [15:0] M_current_counter_d, M_current_counter_q = 1'h0;
  reg [15:0] M_temp_var_d, M_temp_var_q = 1'h0;
  reg [15:0] M_current_timer_d, M_current_timer_q = 1'h0;
  
  always @* begin
    M_p1_score_d = M_p1_score_q;
    M_current_timer_d = M_current_timer_q;
    M_p1_buttonPress_d = M_p1_buttonPress_q;
    M_current_counter_d = M_current_counter_q;
    M_temp_var_d = M_temp_var_q;
    M_p2_buttonPress_d = M_p2_buttonPress_q;
    M_p2_score_d = M_p2_score_q;
    
    if (we) begin
      
      case (write_address)
        4'h0: begin
          M_p1_score_d = data;
        end
        4'h1: begin
          M_p2_score_d = data;
        end
        4'h2: begin
          M_p1_buttonPress_d = data;
        end
        4'h3: begin
          M_p2_buttonPress_d = data;
        end
        4'h7: begin
          M_current_counter_d = data;
        end
        4'h8: begin
          M_current_timer_d = data;
        end
        4'hf: begin
          M_temp_var_d = data;
        end
      endcase
    end
    
    case (read_address_a)
      4'h0: begin
        out_a = M_p1_score_q;
      end
      4'h1: begin
        out_a = M_p2_score_q;
      end
      4'h2: begin
        out_a = M_p1_buttonPress_q;
      end
      4'h3: begin
        out_a = M_p2_buttonPress_q;
      end
      4'h7: begin
        out_a = M_current_counter_q;
      end
      4'h8: begin
        out_a = M_current_timer_q;
      end
      4'hf: begin
        out_a = M_temp_var_q;
      end
      default: begin
        out_a = 1'h0;
      end
    endcase
    
    case (read_address_b)
      4'h0: begin
        out_b = M_p1_score_q;
      end
      4'h1: begin
        out_b = M_p2_score_q;
      end
      4'h2: begin
        out_b = M_p1_buttonPress_q;
      end
      4'h3: begin
        out_b = M_p2_buttonPress_q;
      end
      4'h7: begin
        out_b = M_current_counter_q;
      end
      4'h8: begin
        out_b = M_current_timer_q;
      end
      4'hf: begin
        out_b = M_temp_var_q;
      end
      default: begin
        out_b = 1'h0;
      end
    endcase
    all_scores[0+15-:16] = M_p1_score_q;
    all_scores[16+15-:16] = M_p2_score_q;
    all_buttons[0+1-:2] = M_p1_buttonPress_q[0+1-:2];
    all_buttons[2+1-:2] = M_p2_buttonPress_q[0+1-:2];
    out = M_current_timer_q;
    counter_out = M_current_counter_q;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_p1_score_q <= 1'h0;
      M_p2_score_q <= 1'h0;
      M_p1_buttonPress_q <= 1'h0;
      M_p2_buttonPress_q <= 1'h0;
      M_current_counter_q <= 1'h0;
      M_temp_var_q <= 1'h0;
      M_current_timer_q <= 1'h0;
    end else begin
      M_p1_score_q <= M_p1_score_d;
      M_p2_score_q <= M_p2_score_d;
      M_p1_buttonPress_q <= M_p1_buttonPress_d;
      M_p2_buttonPress_q <= M_p2_buttonPress_d;
      M_current_counter_q <= M_current_counter_d;
      M_temp_var_q <= M_temp_var_d;
      M_current_timer_q <= M_current_timer_d;
    end
  end
  
endmodule
