/*
   This file was generated automatically by Alchitry Labs version 1.1.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module multnn1_5 (
    input clk,
    input rst,
    input ale,
    input ble,
    input asel,
    input bsel,
    input [7:0] n,
    output reg [7:0] debug,
    output reg [7:0] debug1,
    output reg [7:0] out
  );
  
  
  
  reg [7:0] regAout;
  
  reg [7:0] regBout;
  
  reg [7:0] regAin;
  
  reg [7:0] regBin;
  
  reg [7:0] mulOut;
  
  reg [7:0] subOut;
  
  wire [8-1:0] M_regA_out;
  reg [1-1:0] M_regA_en;
  reg [8-1:0] M_regA_data;
  register_7 regA (
    .clk(clk),
    .rst(rst),
    .en(M_regA_en),
    .data(M_regA_data),
    .out(M_regA_out)
  );
  wire [8-1:0] M_regB_out;
  reg [1-1:0] M_regB_en;
  reg [8-1:0] M_regB_data;
  register_7 regB (
    .clk(clk),
    .rst(rst),
    .en(M_regB_en),
    .data(M_regB_data),
    .out(M_regB_out)
  );
  
  always @* begin
    M_regA_en = ale;
    M_regB_en = ble;
    regAout = M_regA_out;
    regBout = M_regB_out;
    out = regAout;
    mulOut = regAout * regBout;
    subOut = regBout - 1'h1;
    if (asel == 1'h0) begin
      regAin = mulOut;
    end else begin
      regAin = 8'h01;
    end
    if (bsel == 1'h0) begin
      regBin = n;
    end else begin
      regBin = subOut;
    end
    M_regA_data = regAin;
    M_regB_data = regBin;
    debug = regBout;
    debug1 = regAout;
  end
endmodule
