/*
   This file was generated automatically by Alchitry Labs version 1.1.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder16_10 (
    input alufn0,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] out,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] sum;
  
  reg [15:0] xb;
  
  always @* begin
    if (alufn0 == 1'h0) begin
      sum = $signed(a) + $signed(b);
    end else begin
      sum = $signed(a) - $signed(b);
    end
    if (sum == 1'h0) begin
      z = 1'h1;
    end else begin
      z = 1'h0;
    end
    n = sum[15+0-:1];
    out = sum;
    xb = b ^ alufn0;
    v = a[15+0-:1] & xb[15+0-:1] & ~sum[15+0-:1] + ~a[15+0-:1] & ~xb[15+0-:1] & sum[15+0-:1];
  end
endmodule
