/*
   This file was generated automatically by Alchitry Labs version 1.1.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter16_11 (
    input [15:0] a,
    input [15:0] b,
    input [1:0] alufn10,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    
    case (alufn10)
      2'h0: begin
        out = a << b[0+4-:5];
      end
      2'h1: begin
        out = a >> b[0+4-:5];
      end
      2'h3: begin
        out = a >>> b[0+4-:5];
      end
      default: begin
        out = a;
      end
    endcase
  end
endmodule
