/*
   This file was generated automatically by Alchitry Labs version 1.2.0.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [2:0] customout,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [8-1:0] M_seqplustwo_out;
  seq_plus_twoSlow_1 seqplustwo (
    .clk(clk),
    .rst(rst),
    .out(M_seqplustwo_out)
  );
  
  wire [8-1:0] M_seqplusvary_out;
  seq_plus_varySlow_2 seqplusvary (
    .clk(clk),
    .rst(rst),
    .out(M_seqplusvary_out)
  );
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_3 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    led = 8'h00;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    customout = 3'h7;
    io_led[0+7-:8] = M_seqplustwo_out;
    io_led[16+7-:8] = M_seqplusvary_out;
  end
endmodule
